version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: install raiden deps
          command: cd raiden_demo/raiden-pisa-daemon && npm install
      - run:
          name: build pisa
          command: npm run build
      - run:
          name: install parity
          command: bash <(curl https://get.parity.io -L) -r stable
      - run:
          name: test
          command: npm run test-coverage
      - run:
          name: test-integration
          command: npm run test-integration
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: ./logs/
      - store_artifacts:
          path: coverage/coverage-summary.json
      - codecov/upload: 
          file: coverage/coverage.lcov
          token: 8840cab9-3613-45d2-9505-8ce7fa6c2cf7
workflows:
  version: 2
  build:
    jobs:
      - build