version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: submodule 
          command: git submodule init && git submodule update 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: build kitsune
          command: npm run build-kitsune
      - run:
          name: build pisa
          command: npm run build
      - run:
          name: install parity
          command: bash <(curl https://get.parity.io -L) -r stable
      - run:
          name: test
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - build