version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: submodule 
          command: git submodule init && git submodule update 
      - run:
          name: install dependencies
          command: |
              apk update
              apk add nodejs python python-dev make gcc g++ py-pip libressl-dev libffi-dev
              pip install docker-compose
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - run:
          name: install
          command: npm install
      - run:
          name: build kitsune
          command: npm run build-kitsune
      - run:
          name: build pisa
          command: npm run build
      - setup_remote_docker
      - run:
          name: test
          command: npm run test
workflows:
  version: 2
  build:
    jobs:
      - build
